---
spring:
  profiles: default

---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soa-book-api-users
    username: root
    password: kirkovg

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update

---
spring:
  profiles: test

spring.jpa:
  hibernate:
    ddl-auto: create-drop

---
spring:
  profiles: local

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://book-api-mysql:3306/demo
  username: dbuser
  password: dbp4ss

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update

eureka:
  client:
    service-url:
     defaultZone: http://book-api-eureka:8761/eureka/
