---
spring:
  profiles: default

---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soa-book-api-users
    username: root
    password: kirkovg

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update

---
spring:
  profiles: test

spring.jpa:
  hibernate:
    ddl-auto: create-drop

---
spring:
  profiles: local

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://my-mysql:3306/demo
  username: dbuser
  password: dbp4ss

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update

---
logging:
  level:
    org:
      springframework:
        security: debug


#eureka:
#  client:
#    service-url:
#     defaultZone: http://my-eureka:8761/eureka/
