version: '2'
services:
  book-api-traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=dck.mojserver.mk
    labels:
      - "traefik.enable=false"
    ports:
      - "18000:80"
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  book-api-eureka:
    image: soa-book-api/eureka
    labels:
      - "traefik.port=8761"
      - "traefik.backend=book-api-eureka"
      - "traefik.frontend.rule=PathPrefixStrip:/book-api-eureka"
    expose:
      - "8761"
    ports:
      - "8761:8761"

  book-api-zuul:
    image: soa-book-api/zuul
    labels:
      - "traefik.port=8080"
      - "traefik.backend=book-api-zuul"
      - "traefik.frontend.rule=PathPrefixStrip:/book-api-zuul"
    depends_on:
      - book-api-traefik
      - book-api-eureka

  book-api-gateway:
    image: soa-book-api/api-gateway
    labels:
      - "traefik.port=8080"
      - "traefik.backend=book-api-gateway"
      - "traefik.frontend.rule=PathPrefixStrip:/book-api-gateway"
    depends_on:
      - book-api-traefik
      - book-api-eureka
      - book-api-mysql
      - book-api-author
      - book-api-book
      - book-api-genre
      - book-api-random-search
      - book-api-rating
      - book-api-user
      - book-api-user-preferences
      - book-api-zuul

  book-api-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbp4ss
      MYSQL_DATABASE: demo
    volumes:
      - book-api-datavolume:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  book-api-author:
    image: soa-book-api/author
    labels:
      - "traefik.port=8080"
      - "traefik.backend=book-api-author"
      - "traefik.frontend.rule=PathPrefixStrip:/book-api-author"
    links:
      - book-api-mysql
      - book-api-eureka
    depends_on:
      - book-api-mysql
      - book-api-traefik
      - book-api-eureka

  book-api-book:
    image: soa-book-api/book
    labels:
      - "traefik.port=8080"
      - "traefik.backend=book-api-book"
      - "traefik.frontend.rule=PathPrefixStrip:/book-api-book"
    links:
      - book-api-mysql
      - book-api-eureka
    depends_on:
      - book-api-mysql
      - book-api-traefik
      - book-api-eureka

  book-api-genre:
    image: soa-book-api/genre
    labels:
      - "traefik.port=8080"
      - "traefik.backend=book-api-genre"
      - "traefik.frontend.rule=PathPrefixStrip:/book-api-genre"
    links:
      - book-api-mysql
      - book-api-eureka
    depends_on:
      - book-api-mysql
      - book-api-traefik
      - book-api-eureka

  book-api-random-search:
    image: soa-book-api/random-search
    labels:
      - "traefik.port=8080"
      - "traefik.backend=book-api-random-search"
      - "traefik.frontend.rule=PathPrefixStrip:/book-api-random-search"
    links:
      - book-api-mysql
      - book-api-eureka
    depends_on:
      - book-api-mysql
      - book-api-traefik
      - book-api-eureka

  book-api-rating:
    image: soa-book-api/rating
    labels:
      - "traefik.port=8080"
      - "traefik.backend=book-api-rating"
      - "traefik.frontend.rule=PathPrefixStrip:/book-api-rating"
    links:
      - book-api-mysql
      - book-api-eureka
    depends_on:
      - book-api-mysql
      - book-api-traefik
      - book-api-eureka

  book-api-user:
    image: soa-book-api/user
    labels:
      - "traefik.port=8080"
      - "traefik.backend=book-api-user"
      - "traefik.frontend.rule=PathPrefixStrip:/book-api-user"
    links:
      - book-api-mysql
      - book-api-eureka
    depends_on:
      - book-api-mysql
      - book-api-traefik
      - book-api-eureka

  book-api-user-preferences:
    image: soa-book-api/user-preferences
    labels:
      - "traefik.port=8080"
      - "traefik.backend=book-api-user-preferences"
      - "traefik.frontend.rule=PathPrefixStrip:/book-api-user-preferences"
    links:
      - book-api-mysql
      - book-api-eureka
    depends_on:
      - book-api-mysql
      - book-api-traefik
      - book-api-eureka

volumes:
  book-api-datavolume: {}
