---
spring:
  profiles: default
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soa-book-api-ratings
    username: root
    password: kirkovg

---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create-drop
---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://book-api-mysql:3306/demo
    username: dbuser
    password: dbp4ss

---
logging:
  level:
    org:
      springframework:
        security: debug


eureka:
  client:
    service-url:
     defaultZone: http://book-api-eureka:8761/eureka/
